#!/bin/bash

#get the list of projects
projects=$(kubectl get ns)

#check if the project exists. If it does, use it.
if [[ $projects == *"$1"* ]]; then
  GREEN='\033[0;32m' 
  NC='\033[0m' # No Color
  kubectl config set-context --current --namespace=$1
  echo -e "${GREEN}Project switched to $1.${NC}"

#if the project does not exist,

else
  RED='\033[0;31m'
  NC='\033[0m' # No Color
  echo -e "${RED}Error:${NC} The given project ${RED}$1${NC} does not exist. Please check the name of your project."
fi

